#pragma once

/**
 * @file entity_id.h
 * @brief Defines the EntityID strong type used throughout the Systemcraft engine.
 */

#include <cstdint>
#include "entt\entt.hpp"

/**
 * @struct EntityID
 * @brief A strongly typed wrapper struct for Entity IDs to ensure type safety.
 * * By wrapping the raw integer in a struct, we prevent systems (like Economy
 * or Transport) from accidentally passing random numbers or tile coordinates
 * into functions that require a valid ECS entity.
 */
struct EntityID
{
    /**
     * @var raw_id
     * @brief The underlying 32-bit unsigned integer representing the entity.
     * * This is the actual number generated by the EntityManager and used by
     * the EnTT registry under the hood.
     */
    uint32_t raw_id;

    /**
     * @brief Checks if this EntityID is currently empty or invalid.
     * * Compares the raw_id against EnTT's reserved null value (entt::null)
     * which is typically the maximum value of a uint32_t.
     * * @return true If the ID represents a null/invalid entity.
     * @return false If the ID contains a valid entity number.
     */
    bool IsNull() const
    {
        return EntityID::raw_id==static_cast<uint32_t>(entt::null);
    }
};
