#pragma once

#include <cstdint>

/**
 * @file global_config.hpp
 * @brief Defines the runtime configuration parameters for a simulation instance.
 * @details Loaded from disk prior to initialization. Passed to all subsystems to define scenario parameters, map generation, and difficulty bounds.
 */

/**
 * @struct GlobalConfig
 * @brief The master runtime configuration payload.
 * @details Contains default values representing a "Standard" difficulty sandbox start. These are intended to be overwritten by a file loader before the simulation begins.
 */
struct GlobalConfig {

    /**
     * @name World Generation
     * @brief Parameters governing the physical bounds and starting state of the grid.
     */
    ///@{
    /** @brief The width of the simulation map in tiles. */
    uint32_t map_width_tiles = 256;

    /** @brief The height of the simulation map in tiles. */
    uint32_t map_height_tiles = 256;

    /** @brief The deterministic seed for procedural generation. A value of 0 indicates a random seed should be generated. */
    uint32_t random_seed = 0;
    ///@}

    /**
     * @name Chronology
     * @brief Parameters governing the starting era of the scenario.
     */
    ///@{
    /** @brief The chronological starting year (e.g., 1950, 2026). Drives initial technology unlocks. */
    uint32_t starting_year = 2000;
    ///@}

    /**
     * @name Scenario & Difficulty Modifiers
     * @brief Multipliers applied on top of the compile-time Economic Constants to scale difficulty.
     */
    ///@{
    /** @brief Multiplier applied to all construction and infrastructure costs. (>1.0 = harder) */
    float construction_cost_multiplier = 1.0f;

    /** @brief Multiplier applied to all base tax revenue collection. (<1.0 = harder) */
    float tax_revenue_multiplier = 1.0f;

    /** @brief Multiplier applied to the health penalty generated by industrial zones. (>1.0 = harder) */
    float pollution_impact_multiplier = 1.0f;

    /** @brief The starting treasury balance in raw currency units. */
    float starting_treasury = 5000000.0f;
    ///@}
};